version: "3.5"

services:

  node:
    image: kkarczmarczyk/node-yarn:latest
    volumes:
    - ./app/app:/workspace
    - ./app/app/docker_node_modules:/workspace/node_modules
    - ./app/app/node_modules:/workspace/external_node_modules
    command: >
      bash -c "cd /workspace
      && yarn
      && yarn build"

  ui:
    container_name: dev_pledge_ui
    image: php:7.2-apache
    environment:
      docker: "true"
      production: "false"
    env_file:
      - .app-dev-env
      - .sentry-env
    volumes:
      - ./app/app/build:/var/www/html/build:cached
      - ./api:/var/www/html/api:cached
      - ./vendor:/var/www/html/vendor:cached
    expose:
      - 80
    networks:
      - default
      - sentry_network
      - cache_network

  mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
     - ./data/mysql:/var/lib/mysql:cached
    ports:
      - 3313:3306

networks:
  default:
    name: devpledge_ui

  sentry_network:
    external:
      name: global_sentry

  cache_network:
    external:
      name: devpledge_cache


