version: "3.5"

services:

  ui:
    build:
      context: .
      dockerfile: ui.dockerfile
    environment:
      docker: "true"
      production: "false"
    env_file:
    #create a .sentryenv with SENTRY_DSN=...
      - .sentryenv
    volumes:
      - .:/var/www:cached
      - ./logs:/var/log:cached
    expose:
      - 9000
      - 9501
    networks:
      - default
      - sentry_network

  mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
     - ./data/mysql:/var/lib/mysql:cached
    ports:
      - 3313:3306

networks:
  default:
    name: devpledge_ui

  sentry_network:
    external:
      name: global_sentry


