version: "3.5"

services:

  node:
    container_name: devpledge_building_ui
    image: kkarczmarczyk/node-yarn:latest
    volumes:
    - ./app/app:/workspace
    - ./app/app/docker_node_modules:/workspace/node_modules
    - ./app/app/node_modules:/workspace/external_node_modules
    command: >
      bash -c "cd /workspace
      && [ -d build ] || mkdir build
      && yarn
      && yarn build"

networks:
  default:
    name: devpledge_ui_build