version: "3.5"

services:

  node:
    image: kkarczmarczyk/node-yarn:latest
    volumes:
    - ./app/app:/workspace
    - ./app/app/docker_node_modules:/workspace/node_modules
    - ./app/app/node_modules:/workspace/external_node_modules
    command: >
      bash -c "cd /workspace
      && yarn
      && yarn build"

  ui-api-composer:
    image: twosee/swoole-coroutine
    working_dir: /app/src
    volumes:
      - ./api:/app/src
    command: composer install

  ui:
    container_name: dev_pledge_ui
    image: php:7.2-apache
    environment:
      docker: "true"
      production: "false"
    env_file:
      - .app-dev-env
      - .sentry-env
    volumes:
      - ./app/app/build:/var/www/html/build:cached
      - ./api:/var/www/html/api:cached
    expose:
      - 80
    networks:
      - default
      - sentry_network
      - cache_network

networks:
  default:
    name: devpledge_ui

  sentry_network:
    external:
      name: global_sentry

  cache_network:
    external:
      name: devpledge_cache


