version: "3.5"

services:

  node:
    image: node
    volumes:
      - ./app/test:/home/node/app
    command: >
      bash -c "cd /home/node/app
      && npm install
      && npm run-script build"

  ui:
    image: httpd
    environment:
      docker: "true"
      production: "false"
    env_file:
    #create a .sentryenv with SENTRY_DSN=...
      - .sentryenv
    volumes:
      - ./app/test/build:/usr/local/apache2/htdocs:cached
    expose:
      - 80
    networks:
      - default
      - sentry_network

  mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
     - ./data/mysql:/var/lib/mysql:cached
    ports:
      - 3314:3306

networks:
  default:
    name: devpledge_ui

  sentry_network:
    external:
      name: global_sentry


